### ISSUE TITLE
Adding local dependencies to virtual projects doesn't update pyproject.toml with correct path

### ISSUE THREAD

**Issue by ma-sadeghi** [astral-sh/rye#800] opened 2024-02-27 12:38 UTC
### Steps to Reproduce

```shell
# Clone a repository to be used as a local package
git clone https://github.com/AUTODIAL/AutoEIS/
mkdir proj
cd proj
rye init --virtual
rye add autoeis --path ../AutoEIS/
```

### Expected Result

AutoEIS to be successfully added as a local dependency

### Actual Result

```shell
❯ rye add autoeis --path ../AutoEIS/
Added autoeis @ file:///AutoEIS as regular dependency
Reusing already existing virtualenv
Generating production lockfile: /home/amin/Code/battery-degradation/requirements.lock
error: Distribution not found at: file:///AutoEIS
error: could not write production lockfile for project

Caused by:
    failed to generate lockfile
```

`pyproject.toml` after this command:
```toml
...
dependencies = [
    "autoeis @ file:///AutoEIS",
]
...
```
It seems that `rye` didn't update `pyproject.toml` with the correct path of the local dependency.

### Version Info

```shell
❯ rye --version
rye 0.27.0
commit: 0.27.0 (43ee4fce0 2024-02-26)
platform: linux (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: true
```

### Stacktrace

I don't think `rye` crashed, but just in case:

```shell
❯ RUST_BACKTRACE=1 rye add autoeis --path ../AutoEIS/
Added autoeis @ file:///AutoEIS as regular dependency
Reusing already existing virtualenv
Generating production lockfile: /home/amin/Code/battery-degradation/requirements.lock
error: Distribution not found at: file:///AutoEIS
error: could not write production lockfile for project

Caused by:
    failed to generate lockfile

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: rye::lock::generate_lockfile
   2: rye::lock::update_single_project_lockfile
   3: rye::sync::sync
   4: rye::sync::autosync
   5: rye::cli::add::execute
   6: rye::cli::execute
   7: rye::main
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: std::rt::lang_start::{{closure}}
  10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  11: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  12: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  13: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  14: std::rt::lang_start_internal::{{closure}}
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  15: std::panicking::try::do_call
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  16: std::panicking::try
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  17: std::panic::catch_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  18: std::rt::lang_start_internal
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  19: main
```

**Comment by bluss** [comment] 2024-02-28 09:09
This is a change in behaviour since rye add started using uv, I think.

**Comment by ma-sadeghi** [comment] 2024-02-28 09:59
It works fine though on regular projects, which also I believe uses `uv`, right?

**Comment by bluss** [comment] 2024-02-28 10:03
it will end up doing slightly different things depending on build backend. The relative path support is underdeveloped. I think it's something like this:

If the current project uses hatchling -> it resolves to absolute path and maybe it works fine from there.
If the current project uses nothing (virtual) or pdm -> it emits a file URL using ${PROJECT_ROOT} and it seems to not survive the trip through uv from there.

**Comment by cnpryer** [comment] 2024-02-28 20:14
Yea FWIW if I unset use-uv I'll get this with the example provided

```
@cnpryer ➜ /workspaces/proj (main) $ rye config --unset behavior.use-uv
@cnpryer ➜ /workspaces/proj (main) $ rye add autoeis --path ../AutoEIS
Added autoeis @ file:///${PROJECT_ROOT}/../AutoEIS as regular dependency
```

**Comment by cnpryer** [comment] 2024-02-28 20:22
and from the resulting toml file 
```toml
[project]
# ...
dependencies = [
    "autoeis @ file:///${PROJECT_ROOT}/../AutoEIS",
]
# ...
```

**Comment by cnpryer** [comment] 2024-02-28 20:50
> [...] If the current project uses nothing (virtual) or pdm -> it emits a file URL using ${PROJECT_ROOT} and that seems to not survive the trip through uv from there.


Yea so I guess this is potentially a `uv` issue? I haven't looked deep enough yet, but at a high level if you provide `uv` with an absolute path (via Rye) the absolute path survives the trip. So you don't hit the lockfile issue.

```diff
diff --git a/rye/src/cli/add.rs b/rye/src/cli/add.rs
index 52162d3..050e037 100644
--- a/rye/src/cli/add.rs
+++ b/rye/src/cli/add.rs
@@ -170,7 +170,7 @@ impl ReqExtras {
                         path.display()
                     )
                 })?;
-                Url::from_file_path(Path::new("/${PROJECT_ROOT}").join(rv)).unwrap()
+                Url::from_file_path(base.as_path().join(rv)).unwrap()
```

Before:
```
rye on  cp-virtual-project [✘?] via 🐍 v3.11.1 via 🦀 v1.76.0 
❯ rm -rf proj 

rye on  cp-virtual-project [✘?] via 🐍 v3.11.1 via 🦀 v1.76.0 
❯ ./target/debug/rye init proj --virtual                             
success: Initialized virtual project in /Users/chrispryer/github/rye/proj
  Run `rye sync` to get started

rye on  cp-virtual-project [✘?] via 🐍 v3.11.1 via 🦀 v1.76.0 
❯ cd proj 

rye/proj on  cp-virtual-project [✘?] is 📦 v0.1.0 via 🐍 v3.11.1 
❯ ../target/debug/rye add testpypi_package --path ../testpypi-package
Added testpypi-package @ file:///testpypi-package as regular dependency
Reusing already existing virtualenv
Generating production lockfile: /Users/chrispryer/github/rye/proj/requirements.lock
error: Distribution not found at: file:///testpypi-package
error: could not write production lockfile for project

Caused by:
    failed to generate lockfile
```

After:
```
rye on  cp-virtual-project [✘!?] via 🐍 v3.11.1 via 🦀 v1.76.0 
❯ rm -rf proj 

rye on  cp-virtual-project [✘!?] via 🐍 v3.11.1 via 🦀 v1.76.0 
❯ ./target/debug/rye init proj --virtual                             
success: Initialized virtual project in /Users/chrispryer/github/rye/proj
  Run `rye sync` to get started

rye on  cp-virtual-project [✘!?] via 🐍 v3.11.1 via 🦀 v1.76.0 
❯ cd proj 

rye/proj on  cp-virtual-project [✘!?] is 📦 v0.1.0 via 🐍 v3.11.1 
❯ ../target/debug/rye add testpypi_package --path ../testpypi-package
Added testpypi-package @ file:///Users/chrispryer/github/rye/testpypi-package as regular dependency
Reusing already existing virtualenv
Generating production lockfile: /Users/chrispryer/github/rye/proj/requirements.lock
Generating dev lockfile: /Users/chrispryer/github/rye/proj/requirements-dev.lock
Installing dependencies
Installed 7 packages in 26ms
 + pandas==2.2.1
 + polars==0.20.11
 + python-dateutil==2.8.2
 + pytz==2024.1
 + six==1.16.0
 + testpypi-package==0.1.0 (from file:///Users/chrispryer/github/rye/testpypi-package)
 + tzdata==2024.1
Done!
```

pyproject.toml
```toml
[project]
# ...
dependencies = [
    "testpypi-package @ file:///Users/chrispryer/github/rye/testpypi-package",
]
# ...
```

**Comment by bluss** [comment] 2024-02-28 21:35
Short term this is a rye bug: it's using uv in the wrong way.

But it's also a "regression" that virtual projects support relative path dependencies without uv, but with uv they don't. That invocation with the absolute path put your username into the pyproject.toml file, and that's not very portable.

**Comment by cnpryer** [comment] 2024-02-28 21:39
Yea definitely worth investigating. I might be able to check this out more later this week if no one gets to it.

**Comment by cnpryer** [comment] 2024-02-29 01:32
I believe this is where our requirement might be truncated to /some/path due to the way the string is encoded for the url, but I could be wrong. Barely dug.

https://github.com/astral-sh/rye/blob/2111778b316555de0c3d459056e7e9d4ed56119d/rye/src/cli/add.rs#L487

**Comment by cnpryer** [comment] 2024-02-29 01:36
From that very minimal debug.
```
[rye/src/cli/add.rs:488:9] urlencoding::decode(&String::from_utf8_lossy(&rv.stdout)) = Ok(
    "package @ file:///${PROJECT_ROOT}/../package\n",
)
[rye/src/cli/add.rs:490:9] &new_req = Requirement {
    name: "package",
    extras: None,
    version_or_url: Some(
        Url(
            Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/package",
                query: None,
                fragment: None,
            },
        ),
    ),
    marker: None,
}
```

**Comment by cnpryer** [comment] 2024-02-29 02:12
Hacked together a fix for this example specifically. I'll look into it more and see if I can PR something later this week.

```
@cnpryer ➜ /workspaces/rye/project (main) $ ../target/debug/rye add package --path ../package/
[rye/src/cli/add.rs:499:9] &new_req = Requirement {
    name: "package",
    extras: None,
    version_or_url: Some(
        Url(
            Url {
                scheme: "file",
                cannot_be_a_base: false,
                username: "",
                password: None,
                host: None,
                port: None,
                path: "/$%7BPROJECT_ROOT%7D/../package",
                query: None,
                fragment: None,
            },
        ),
    ),
    marker: None,
}
Added package @ file:///${PROJECT_ROOT}/../package as regular dependency
Reusing already existing virtualenv
Generating production lockfile: /workspaces/rye/project/requirements.lock
Generating dev lockfile: /workspaces/rye/project/requirements-dev.lock
Installing dependencies
Resolved 1 package in 0ms
   Built package @ file:///workspaces/rye/package                                                                                                                 Downloaded 1 package in 251ms
Installed 1 package in 0ms
 + package==0.1.0 (from file:///workspaces/rye/package)
Done!
```

```toml
dependencies = [
    "package @ file:///${PROJECT_ROOT}/../package",
]
```

**Closed** 2024-03-06 20:30 UTC
