### ISSUE TITLE
rye build hangs

### ISSUE THREAD

**Issue by arshan-ritual** [astral-sh/rye#961] opened 2024-03-28 21:09 UTC
### Steps to Reproduce

```
rye init my-project
cd my-project
rye sync
rye build
```

### Expected Result

For the build to happen very quickly

### Actual Result

```bash
(base) ➜  arsh-monorepo git:(main) ✗ rye build
building arsh-monorepo
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatchling)
```

### Version Info

```
rye 0.31.0
commit: 0.31.0 (72e239b8f 2024-03-22)
platform: macos (aarch64)
self-python: cpython@3.12.2
symlink support: true
uv enabled: true
```

**Comment by mitsuhiko** [comment] 2024-03-29 09:04
Unfortunately I cannot reproduce this. However the step where it seems to be stuck for you is in `hatchling` so it might be that for some reason hatchling misbehaves on your system. Maybe you can reproduce this behavior outside of rye and with hatchling alone.

Going to close this here for now. Feel free to reopen if you can exclude this to be a hatchling issue.

**Closed by mitsuhiko** 2024-03-29 09:04 UTC

**Comment by arshan-ritual** [comment] 2024-03-29 13:30
I found out what the issue was so posting it here in case someone else runs into it. I was going to build & publish to a private pypi repository on google cloud. I had added a line to my `~/.config/pip/pip.conf`:

```
[global]
extra-index-url = <url-to-my-pypi>
```

And for some reason hatchling would hang when attempting to build.
