### ISSUE TITLE
Windows installer (v0.0.30) triggers Windows Defender SmartScreen

### ISSUE THREAD

**Issue by ma-sadeghi** [astral-sh/rye#911] opened 2024-03-20 18:41 UTC
![image](https://github.com/astral-sh/rye/assets/14086031/1d218332-298e-4e11-9e0a-fb9d655d79a2)

**Comment by mitsuhiko** [comment] 2024-03-20 20:21
Duplicate of #468

**Closed by mitsuhiko** 2024-03-20 20:21 UTC
