### ISSUE TITLE
Rye's version of Python leads to `clang not found` errors

### ISSUE THREAD

**Issue by sdiebolt** [astral-sh/rye#836] opened 2024-03-04 15:15 UTC
### Steps to Reproduce

First, let me thank you for creating rye and improving it so quickly! It is truly a game-changer and makes managing Python projects a breeze. :rocket: 

On Ubuntu 22.04:

1. Install rye with `uv` as preferred package installer, Python installed and managed by Rye and `cpython@3.12` as default toolchain.
2. Create a project with rye: `rye init test`
3. Add `pycairo` using `rye add pycairo`.

This issue happens with other Python packages, e.g. `spatialgeometry`.

### Expected Result

`pycairo` should be correctly installed in the virtual environment created by `rye`.

### Actual Result

I get the following error:

```bash
Added pycairo>=1.26.0 as regular dependency
Reusing already existing virtualenv
Generating production lockfile: /home/sdiebolt/Documents/Work/physmed-seminars/test/requirements.lock
Generating dev lockfile: /home/sdiebolt/Documents/Work/physmed-seminars/test/requirements-dev.lock
Installing dependencies
   Built file:///home/sdiebolt/Documents/Work/physmed-seminars/test                                     Built 1 editable in 298ms
Resolved 1 package in 0ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: pycairo==1.26.0
  Caused by: Failed to build: pycairo==1.26.0
  Caused by: Build backend failed to build wheel through `build_wheel()`:
--- stdout:
running bdist_wheel
running build
running build_py
creating build/lib.linux-x86_64-cpython-312
creating build/lib.linux-x86_64-cpython-312/cairo
copying cairo/__init__.py -> build/lib.linux-x86_64-cpython-312/cairo
copying cairo/__init__.pyi -> build/lib.linux-x86_64-cpython-312/cairo
copying cairo/py.typed -> build/lib.linux-x86_64-cpython-312/cairo
running build_ext
--- stderr:
error: [Errno 2] No such file or directory: 'clang'
---
error: Installation of dependencies failed
```

Indeed, I don't have `clang` installed on my machine. However, `clang` isn't required to build Python packages when using the OS Python.

I've noticed that the version of Python installed by rye is compiled using clang, whereas the OS Python from my machine is compiled using gcc. Indeed, when creating a virtual environment using my OS gcc-compiled Python and installing `pycairo`, the build is successfully done using `gcc`. I'm not at all familiar with how Python packages are built however, but I would expect rye to install a Python version that uses the building toolchain available on the host? Or is clang a requirement to use `rye`?

### Version Info

```
rye 0.27.0
commit: 0.27.0 (43ee4fce0 2024-02-26)
platform: linux (x86_64)
self-python: cpython@3.12
symlink support: true
uv enabled: true
```

**Comment by bluss** [comment] 2024-03-04 20:58
I saw this too and just set CC=gcc and didn't think so much about it (so that should work - does it work for you?), but it sounds like can be improved.

**Comment by mitsuhiko** [comment] 2024-03-04 21:06
This is basically what #646 should resolve. Work has not started yet.

Closing as duplicate of #646

**Closed** 2024-03-04 21:06 UTC
Labels: duplicate

**Comment by sdiebolt** [comment] 2024-03-04 21:45
> I saw this too and just set CC=gcc and didn't think so much about it (so that should work - does it work for you?), but it sounds like can be improved.

Yes, installing clang or setting `CC=gcc` works as expected! However, this is the first time I encountered such an issue, and it isn't very practical especially for CI/CD pipelines that need to be modified to account for this...

Thanks for the quick update @mitsuhiko!

**Comment by amano-takahisa** [comment] 2024-06-02 07:36
I had the similar error to @sdiebolt when I tried to install `gdal` package with `rye add gdal`.
In my case, I also had `clang++` not found error, but the following worked so far.

```console
CC=gcc CXX=g++ rye add gdal
```
I share this as a temporary solution for those who are facing similar problems.

**Comment by quinn-dougherty** [comment] 2024-06-15 16:25
experienced this on many dependencies (especially ones that require cpyparsing). triple-checked that clang and gcc were on the ephemeral shell, which silenced the clang version of the error but didn't work for gcc. amano-takahisa's solution got me through it!
